# Data Cleaning

## Objective
The objective of this notebook is to clean the dataset by checking for missing values, duplicate records, incorrect data types, and preparing the data for analysis.

In [6]:
import os
print(os.listdir())

['.config', 'ApexPlanet_DataAnalytics_Dataset.xlsx', 'sample_data']

In [11]:
import pandas as pd
df = pd.read_excel('ApexPlanet_DataAnalytics_Dataset.xlsx')
df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   object
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            980 non-null    float64
 5   Gender         1000 non-null   object
 6   City           987 non-null    object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 93.9+ KB

In [14]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age              20
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df = df.drop_duplicates()

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.dtypes

Order_ID          object
Order_Date        object
Customer_ID       object
Customer_Name     object
Age              float64
Gender            object
City              object
Product           object
Category          object
Quantity           int64
Unit_Price       float64
Total_Sales      float64
dtype: object

In [19]:
df.shape

(1000, 12)

In [20]:
df.to_csv("clean_data.csv", index=False)

# Conclusion

The dataset was successfully cleaned by:

- Checking missing values
- Removing duplicate records
- Verifying data types
- Saving the cleaned dataset

The cleaned dataset is now ready for Exploratory Data Analysis (EDA).